// src/app/app.config.ts
import { ApplicationConfig, importProvidersFrom, provideZoneChangeDetection } from '@angular/core';
import { provideRouter, withPreloading, PreloadAllModules } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideIonicAngular } from '@ionic/angular/standalone';
import {
  SocialLoginModule,
  SOCIAL_AUTH_CONFIG,
  GoogleLoginProvider,
  FacebookLoginProvider,
} from '@abacritt/angularx-social-login';
import type { SocialAuthServiceConfig } from '@abacritt/angularx-social-login';
import { environment } from '../environments/environment';
import { addIcons } from 'ionicons';
import {
  personOutline,
  callOutline,
  mailOutline,
  calendarOutline,
  settingsOutline,
  logOutOutline,
  searchOutline,
  constructOutline,
  businessOutline,
  mapOutline,
  searchCircleOutline,
  refreshOutline,
  listOutline,
  arrowForward,
  locationOutline,
  cashOutline,
  starOutline,
  chevronDownCircleOutline,
  notificationsOffOutline,
  homeOutline,
  home,
  trashOutline,
  briefcaseOutline,
  chatbubblesOutline,
  addOutline,
  globeOutline,
  body,
  documentTextOutline,
  fileTrayOutline,
  arrowUpOutline,
  closeCircleOutline,
  // Additional outline icons
  lockClosedOutline,
  logoFacebook,
  logoGoogle,
  logoApple,
  personCircle,
  documentText,
  // Solid/generic icons
  cut,
  paw,
  hammer,
  build,
  // Solid icons
  star,
  business,
  location,
  cash,
  eye,
  calendar,
  person,
  construct,
  addCircle,
  removeCircle,
  search,
  map,
  close,
  checkmarkCircle,
  trash,
  create,
  ellipse,
  closeCircle,
  chevronForward,
  fingerPrint,
  informationCircle,
  save,
  call,
  mail,
  arrowBackOutline,
  bookmarkOutline,
  starHalf,
  chatbubbleEllipsesOutline,
  compass,
  navigateCircle,
  chatbubbleOutline,
  videocam,
  ellipsisVertical,
  happyOutline,
  attachOutline,
  cameraOutline,
  send,
  filterOutline,
  chevronDownOutline,
  checkmarkDoneOutline,
  shieldCheckmarkOutline,
  notificationsOutline,
  documentLockOutline,
  languageOutline,
  contrast,
  informationCircleOutline,
  giftOutline,
  chatbubbles,
  time,
  image,
  alertCircle,
  readerOutline,
  createOutline,
  flashOutline,
  chevronForwardOutline,
  closeOutline,
  trendingUpOutline,
  eyeOutline,
  eyeOffOutline,
  checkmarkCircleOutline,
   logOut,
  camera,
  calendarClearOutline,
  personAdd,
  timeOutline,
  rocketOutline,
  addCircleOutline,
  layersOutline,
  receiptOutline,
  cartOutline,
  cloudUpload,
  storefront,
  flash,
  chevronDown,
  helpCircle,
  globe,
  storefrontOutline,
  handLeftOutline,
  radioButtonOffOutline,
  keyOutline,
  logIn,
  navigateOutline,
  navigate



} from 'ionicons/icons';

import { routes } from './app.routes';
import { authInterceptor, errorInterceptor } from './core/interceptors/auth.interceptor';
import { nativeHttpInterceptor } from './core/interceptors/native-http.interceptor';

// Registrar todos los iconos necesarios
addIcons({
  // Outline variants
  personOutline,
  callOutline,
  mailOutline,
  calendarOutline,
  settingsOutline,
  logOutOutline,
  searchOutline,
  constructOutline,
  businessOutline,
  mapOutline,
  searchCircleOutline,
  refreshOutline,
  listOutline,
  locationOutline,
  cashOutline,
  starOutline,
  chevronDownCircleOutline,
  notificationsOffOutline,
  homeOutline,
  home,
  trashOutline,
  briefcaseOutline,
  chatbubblesOutline,
  addOutline,
  globeOutline,
  documentTextOutline,
  fileTrayOutline,
  arrowUpOutline,
  closeCircleOutline,
  lockClosedOutline,
  logoFacebook,
  logoGoogle,
  logoApple,
  // Solid/regular variants
  star,
  business,
  location,
  cash,
  eye,
  calendar,
  person,
  construct,
  addCircle,
  removeCircle,
  search,
  map,
  close,
  checkmarkCircle,
  trash,
  create,
  ellipse,
  closeCircle,
  chevronForward,
  fingerPrint,
  informationCircle,
  save,
  call,
  mail,
  body,
  arrowBackOutline,
  bookmarkOutline,
  starHalf,
  chatbubbleEllipsesOutline,
  compass,
  navigateCircle,
  chatbubbleOutline,
  videocam,
  ellipsisVertical,
  happyOutline,
  attachOutline,
  cameraOutline,
  send,
  personCircle,
  documentText,
  cut,
  paw,
  hammer,
  build,
  filterOutline,
  chevronDownOutline,
  checkmarkDoneOutline,
  shieldCheckmarkOutline,
  notificationsOutline,
  documentLockOutline,
  languageOutline,
  contrast,
  informationCircleOutline,
  giftOutline,
  chatbubbles,
  // Aliases - mapear nombres simples a iconos existentes
  add: addCircle,
  remove: removeCircle,
  refresh: refreshOutline,
  time,
  lockClosed: lockClosedOutline,
  navigate,
  flashOutline,
  chevronForwardOutline,
  createOutline,
  readerOutline,
  closeOutline,
  timeOutline,
  trendingUpOutline,
  eyeOutline,
  eyeOffOutline,
  logOut,
  camera,
  personAdd,
  rocketOutline,
  addCircleOutline,
  layersOutline,
  receiptOutline,
  cartOutline,
  cloudUpload,
  image,
  arrowForward,
  alertCircle,
  calendarClearOutline,
  checkmarkCircleOutline,
  storefront,
  flash,
  chevronDown,
  handLeftOutline,
  radioButtonOffOutline,
  keyOutline,
  helpCircle,
  globe,
  logIn,
  storefrontOutline,
  navigateOutline,
  list: listOutline
});

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withPreloading(PreloadAllModules)),
    provideHttpClient(withInterceptors([authInterceptor, errorInterceptor, nativeHttpInterceptor])),
    provideIonicAngular({ mode: 'ios' }),
    importProvidersFrom(SocialLoginModule),
    {
      provide: SOCIAL_AUTH_CONFIG,
      useValue: {
        autoLogin: false,
        providers: [
          {
            id: GoogleLoginProvider.PROVIDER_ID,
            provider: new GoogleLoginProvider(environment.googleClientId),
          },
          {
            id: FacebookLoginProvider.PROVIDER_ID,
            provider: new FacebookLoginProvider(environment.facebookAppId),
          },
        ],
        onError: (err: any) => console.error('[SocialAuth] Error:', err),
      } as SocialAuthServiceConfig,
    },
  ]
};